### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by levidrain** [Shuttle/Shuttle.Recall#3]
I'm really interested in this project.   The design and api make a lot of sense to me.   I'm curious about Metadata (the user who made the changes, the IP address, etc).  I don't want to bake this into all of my events.

**Comment by eben-roux** [comment]
Interesting question.

It may be possible to add a type of `Header` collection onto an event.  I do this with my service bus.  However, those headers would need to come from somewhere.  That place is usually a command.  This means that your command would need to carry that information also.  Since event sourcing isn't too concerned with the command side of things I don't quite know how the two would tie up.

The easiest would probably be to create a class containing all your infrastructure/common bits and pass that into your domain:

```
public SomethingDone DoSomething(Actor actor, string someData)
{
    Guard.AgainstNull(actor, "actor");

    actor.Invariant();

    return new SomethingDone
    {
        Actor = actor,
        SomeData = someData
    };
}

public class Actor
{
    public string IPAddress { get; set; }
    public string UserName { get; set; }
    public string MachineName { get; set; }
    public int SomeNumber { get; set; }
}

public static class ActorExtensions
{
    public static void Invariant(this Actor actor)
    {
        if (string.IsNullOrEmpty(actor.IPAddress))
        {
            throw new InvalidOperationException("The IPAddress is required.");
        }

        // ...etc
    }
}
```

It may be worthwhile asking a question on StackOverflow as to the opinion others may have on this.

**Comment by eben-roux** [comment]
There is already a bit of discussion around the metadata topic already.  Here is an [interesting link](https://groups.google.com/forum/#!topic/dddinphp/TPQdlPV6zr0).

I actually like the idea of externalising the metadata.  Once you have a unique event id one could always write the metadata to another store/table using that same id to associate/join later.

**Comment by levidrain** [comment]
Thanks for the link!  I'm not sure I agree that the metadata belongs in a different store.  I think I agree with the commenter, that the data shouldn't be stored _in_ the event, but it should be stored _with_ the event.
Assuming that there is a commit boundary for each command and the command is the source of the metadata, then you shouldn't have to duplicate the metadata for each event right? 
I like that you treat snapshots as just special events, I wonder if something similar could be done with metadata?

**Comment by eben-roux** [comment]
I read on one of the links that it may be difficult to discern what is metadata and what is business data/state.  In the case of metadata I don't quite think that it may have much relevance in the domain.  It is more of an audit/log thing related to a specific event.  For instance, if I have three `CustomerMoved` events, each will change the same state with the result being the last place the customer moved to.  However, those three events may have come from three different users on three different machines.  I guess one _could_ store the last one as the `modifier` of sorts but also only for that piece of the aggregate.

I am somewhat struggling to see how one would use and tie up this metadata.  I definitely has relevance (well, probably) in the read model where changes can be tracked but probably less on the domain side.

Perhaps you can provide some sample with the idea you have w.r.t. how to use this metadata.

I am quite happy extending Recall to handle such scenarios if at all possible.  A PR is also welcome :)

**Comment by levidrain** [comment]
I agree that the domain is not concerned with the metadata.  If for some reason the domain needs data that is also part of the metadata, I think it should duplicated on the event.  I wouldn't pass the metadata to the domain when reloading the aggregate.
Here's what I meant by the commit thing:  (forgive the poor example), say you have command like UpdateCustomerProfile, this would produce events like, CustomerNameChanged, CustomerEmailChanged, CustomerAddressChanged.  All of those events should be treated as one commit (or transaction) since they result from one command.  In that case, I think they would all have the same metadata.  If another user also issued the same command, they would get a different commit with a different set of metadata.
I think the biggest reason why I believe the metadata should be stored with the events is to maintain a sort of 'atomic' nature.
On consuming the metadata, I agree that this is something the projection would want.  In my case, the business wants to show a sort of 'history' for things like customers.  They want to not only see what changed but by who and when.  They don't want to see every event though, it's like a curated view of the history.  My plan was to use a projection and write data to a history table for certain events.  This solves the heterogeneous shape of the events.

**Comment by eben-roux** [comment]
After giving this some more thought: it may be an option to add metadata to the `EventStream` since any new events are added to the `EventStream` and it is then eventually stored to an `IEventStore` implementation.

In this case one could add `EventStream.AddMetadata(object metadata)`.  However, one could also have `EventStream.AddEvent(object event, object metadata)`.  These would be called in the command handler.  I don't know if one would have both.  Adding metadata per event is more granular but the question is whether that is something that is required?

The metadata would be added to the `Event` object anyway.  It would, therefore, be available when read back but still not in the domain per se.

Adding metadata as part of the commit would still require a link to each event though since one would need that data.  I guess each save could be accompanied by a `CommitId` (Guid) and then the metadata would be linked to that.  But that would only work if metadata is not required per event.  I guess one _could_ get away with the "per-commit" metadata and then just have multiple commits (saves) when requiring different metadata per event.

Let me know what you think...

**Comment by levidrain** [comment]
I was thinking about this yesterday too.  I've been trying to think of some sort of data that would be different per event within a single commit.  All the sample metadata I thought of was request related (ip address, user, request headers, etc).   One metadata entry per commit would save on data, but I agree it seems limiting.
I looked at a few other implementations and they all store metadata per event, but they also use metadata to track things like the event type and event version.  So, it makes since that it would be store per event.
I think per event is probably the right approach.

**Comment by eben-roux** [comment]
Now the next question is whether one would need an object or something more predictable.  I am leaning toward a name/value pair (strings) since it is the most versatile and typically metadata is made up of primitive data (no structures).  The issue one would run into with an object for metadata is that the type would also need to be stored and when loaded the projection may need to know the type.  Since it is a given that the projection requires the domain event we can specify the type using a generic:

```
    public interface IEventHandlerContext<out T> where T : class
    {
        ProjectionEvent ProjectionEvent { get; }
        T DomainEvent { get; }
        IThreadState ActiveState { get; }
    }
```

However, where would the metadata fit in?  I guess the easiest, if going with an object, is to use `object` and cast it where necessary.  But that seems a bit odd.  Having a `List<DomainEventHeader>` (or whatever it is called) as a name/value pair is quite easy to implement.

Since you have had a look at other implementations, what would you recommend in this regard?

**Comment by levidrain** [comment]
Most, if not all, of the implementations I've seen use a similar key/value approach.
I wonder if events could just be wrapped in an envelope. Like Metadata<Event> and store that as the event?  You wouldn't need to change the API at all and it would still be strongly typed.  The issue is in the replay, you wouldn't want the 'On' methods to use the envelope.  I wonder if it would be possible to simply allow and interception layer during playback to basically unwrap the event.  
I've not seen anyone do it that way, so it's probably a bad idea.

**Comment by eben-roux** [comment]
Interesting thought...

In fact, I do exactly this with my service bus.  I have a [TransportMessage](https://github.com/Shuttle/Shuttle.Esb/blob/master/Shuttle.Esb/Messages/TransportMessage.cs).  Now I'm wondering why I didnh't consider this intiially... :)

Doesn't seems like a bad idea.  I think my thinking was to, like other implementations, focus on the domain event.  For the projection side of things one probably needs access to some of the bits directly, but that can be exposed/copied by the implementation.  Perhaps something like this then:

```
    [Serializable]
    public class EventMessage
    {
        public EventMessage()
        {
            EventId = Guid.NewGuid();
            DateRegistered = DateTime.MinValue;
            Headers = new List<EventHeader>();
        }

        public byte[] Message { get; set; }

        public Guid EventId { get; set; }
        public int Version { get; set; }
        public long SequenceNumber { get; set; }
        public string CorrelationId { get; set; }
        public string PrincipalIdentityName { get; set; }
        public DateTime DateRegistered { get; set; }
        public string MessageType { get; set; }
        public string AssemblyQualifiedName { get; set; }
        public string EncryptionAlgorithm { get; set; }
        public string CompressionAlgorithm { get; set; }
        public List<EventHeader> Headers { get; set; }
    }

    [Serializable]
    public class EventHeader
    {
        public string Key { get; set; }
        public string Value { get; set; }
    }
```

I could probably get rid of the `ITypeStore` as well as the type is contained in the envelope.  Any `TypeStore` requirement could be an implementation detail for the specific implementation package.

Thanks so much for your thoughts.  It really does help with the design when folks have specific issues or requirements.

**Comment by eben-roux** [comment]
I don't know if you are still having a look at Recall but I've changed the structure in order to make use of an envelope.

**Comment by levidrain** [comment]
It's funny you mentioned this.. i've been working on front end stuff and had just circled back around to the back end a few days ago and noticed it had changed quite a bit.  I'm excited to look into your changes.

**Comment by eben-roux** [comment]
Well, if you *are* actually using it the event store structure has changed quite a bit so all the events would need to be updated.  Don't know if this will cause an issue for you but if it is going to be a hassle please let me know.  I could write a converter of sorts to get the events over to the new structure.

**Comment by levidrain** [comment]
I actually hadn't started using it yet.

**Comment by eben-roux** [comment]
That is actually good news.  If you *do* get around to playing with it please let me know what you think :)
