### ISSUE TITLE
.Net standard and others questions

### ISSUE THREAD

**Issue by joffreynorsys** [Shuttle/Shuttle.Recall#4]
Hello,

I look your differents projects (esb and recall) and i'm very interesting. So i have several questions :
  
* esb and recall solutions are Production ready ? Have you some benchmark ?
* Do you plan to migrate your solution to .Net Standard to use it with .net core ?
* I See you use SQLServer as store. In the context of event sourcing (recall) have you an idea to how manage the event archiving strategy in case of big system with number of event  ?

Thank you for your responses.

**Comment by eben-roux** [comment]
Hi,

Shuttle.Esb has been running in production for quite a number of years at various companies that I have been involved with.

The new version 8.0 release will be more dependency container focused but the inner working hasn't changed.  This version will be released soon.

Shuttle.Recall is somewhat of an experiment but may very be able to handle production loads.  I cannot see why not.  Sql Server should work fine as an events store but since everything is abstracted it is possible to implement any other store as the persistence mechanism.

I'll probably be looking at PostgreSQL next as a persistence store.

As for .net core: I am certainly looking at having the projects run on this platform but I haven't had time to get going on that yet.

**Comment by eben-roux** [comment]
I released v10.0.0 today (13 Feb 2018) that supports .Net 4.6+ as well as .Net Core/Standard 2.0+.

If you do end up using it please log any issues as we deal with any teething problems :)
